### PR TITLE
Fix set default role of User

### PR DESCRIPTION
**Pull request by klacointe**
TheRole.create_admin_role! does't exists anymore, replaced by TheRole.create_admin!

### CODE REVIEW

**Comment by klacointe** [comment]
:satisfied:

Still remains the call to `TheRole.create_admin_role!`

**Comment by the-teacher** [comment]
@klacointe ouch! thanks!

**Comment by the-teacher** [comment]
https://github.com/TheRole/the_role_api/releases/tag/v3.0.3
https://rubygems.org/gems/the_role_api/versions/3.0.3

**Comment by the-teacher** [comment]
@klacointe 

I add you to contributors https://github.com/the-teacher/the_role/blob/master/README.md#contributors
Thanks for help!

**Comment by klacointe** [comment]
@the-teacher thanks! :dancers:

**Pull request closed without merging**
